version: '3.6'

services:
  nginx:
    image: nginx
    networks:
      - nginx
    ports:
      - '${HOST_IP:-0.0.0.0}:80:80'
      - '${HOST_IP:-0.0.0.0}:443:443'
    volumes:
      - './:/var/www/magento/'
      - './docker/nginx/php.conf:/etc/nginx/conf.d/default.conf:ro'
    depends_on:
      - php

  php:
    build:
      context: './docker/php'
      args:
        UID: "${UID}"
    volumes:
      - './:/var/www/magento'
      - '~/.composer/auth.json:/home/sutunam/.composer/auth.json'
    networks:
      - nginx
      - php
    depends_on:
      - sql

  sql:
    image: mariadb:10.4
    env_file:
      - './docker/sql/.env'
    volumes:
      - './docker/sql/data:/var/lib/mysql'
    networks:
      - php

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: sql
    depends_on:
      - sql
    networks:
      - php
    ports:
      - '${PMA_PORT:-8080}:80'

  es:
    build: docker/es/
    networks:
        - php
    volumes:
        - './docker/es/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro'
        - 'esdata:/usr/share/elasticsearch/data'
    environment:
        ES_JAVA_OPTS: "-Xmx512m -Xms512m"

networks:
  nginx:
  php:

volumes:
  esdata:
